name: Hello World Alertify
on:
    push:
        branches:
            - github-actions/initial
jobs:
    hellowrold: 
        runs-on: macos-latest
        steps:
            - name: List before checkout
              run: ls
            - name: Checkout
              uses: actions/checkout@v3 # This is the action that checks out the repository
            - name: List after checkout
              run: ls
