name: List Project
on:
  push:
    branches:
      - gh-actions/init
jobs:
  helloworld:
    runs-on: macos-latest
    steps:
      - name: List before checkout
        run: ls
      - name: Checkout
        uses: actions/checkout@v3
      - name: List after checkout
        run: ls