# 1. INSTALAR FLUTTER
# 2. INSTALAR FLUTTER
# 3. GENERAR UNA APK
# 4. GUARD
#     - flutter analyze
#     - flutter test
# 5. GENERAR IPA
#     - INSTALAR PERFIL TEMPORAL
#     - INSTALAR CERTIFICADOS
# 6. APP DISTRIBUTION CLI
#     - firebase tools

name: FLUTTER_MASTER_1
on:
  push:
    branches:
      - gh-actions/alertify

jobs:
  flutter_master_dev:
    runs-on: macos-latest
    steps:
      - name: COPY .
        uses: actions/checkout@v4
      - name: INSTALACION DE JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: INSTALACION DE FIREBASE TOOLS
        run: npm install -g firebase-tools
      - name: INSTALL FLUTTER
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - run: flutter --version