# 1. INSTALAR FLUTTER

name: FLUTTER_MASTER_1
on:
  push:
    branches:
      - gh-actions/alertify

jobs:
  flutter_master_dev:
    runs-on: macos-latest
    steps:
      - name: COPY .
        uses: actions/checkout@v4
      - run: echo '${{vars.HELLO_WORLD_VAR}}'
      - run: echo '${{secrets.HELLO_VAR_WORLD}}'