name: FLUTTER_MASTER
on:
    push:
        branches:
            - github-action
jobs:
    flutter_master_dev: 
        runs-on: macos-latest
        steps:
            - name: COPY .
              uses: actions/checkou@v4