# 01. INSTALL JAVA
# 02. INSTALL FLUTTER
# 03. GENERAR UNA APK
# 04. GUARD
#   - flutter analyze
#   - flutter test
# 05. GENERAR IPA
#   - INSTALL PERFIL TEMPORAL
#   - INSTALAR CERTIFICADOs
#   - CONFIGURAR KEYCHAIN
# 06. APP DISTRIBUTION CLI
#   - firebase tools

name: FLUTTER_MASTER
on:
    push:
        branches:
            - github-action
jobs:
    flutter_master_dev: 
        runs-on: macos-latest
        steps:
            - name: COPY .
              uses: actions/checkout@v4
            - name: INSTALACION DE JAVA
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '11'
            - name: INSTALL FIREBASE TOOLS
              run: npm install -g firebase-tools

            - name: INSTALL FLUTTER
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: "3.19.5"
            - run: flutter --version
            - name: FLUTTER TEST
              run: flutter test
            - name: FLUTTER ANALYZE
              run: flutter analyze