# 1. INSTALAR FLUTTER 
# 2. INSTALAR FLUTTER
# 3. GENERAR UNA APK
# 4. GUARD
#     - flutter analyze
#     - flutter test
# 5. GENERAR IPA
#     - INSTALAR PERFIL TEMPORAL
#     - INSTALAR CERTIFICADOS
#     - CONFIGURAR KEY CHAIN
# 6. APP DISTRIBUTION CLI
#     - firebase tools
#     - google-application-credential.json
# 7. artifact
# 8. CACHE STRATEGY

name: FLUTTER_MASTER_1
on:
  push:
    branches:
      - gh-actions/alertify

jobs:
  flutter_master_dev:
    runs-on: macos-latest
    env: 
      GOOGLE_APLICATION_CREDENTIAL: google-application-credential.json
    steps:
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules/ 
            **/Users/runner/
          key: ${{ runner.os }}-primes
 
      - name: COPY .
        uses: actions/checkout@v4
      - name: INSTALACION DE JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: INSTALACION DE FIREBASE TOOLS
        run: npm install -g firebase-tools

      - name: INSTALL FLUTTER
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter --version

      - name: FLUTTER TEST
        run: flutter test

      - name: FLUTTER ANALYZE
        run: flutter analyze

      - name: GOOGLE_CREDENTIAL
        shell: bash
        run: |
          echo '${{secrets.JSON_APP_CREDENTIAL_ACCESS}}' | base64 --decode > "google-application-credential.json"

      - name: GENERAR APK
        run: flutter build apk --release
        
      - name: UPLOAD APK DISTRIBUTION
        run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app 1:865785082084:android:44dff0aafa459d9b267cf1 --groups "testers"

      - name: ARTIFACT
        uses: actions/upload-artifact@v4
        with:
          name: apk-and-ipa
          path: |
            build/app/outputs/flutter-apk/app-release.apk